export const SET_RECEIVED_JSON = 'SET_RECEIVED_JSON';
export const SET_RECEIVED_TASK = 'SET_RECEIVED_TASK';
export const RM_TASK = 'RM_TASK';

export const SET_PRIVATE_DICTIONARIES = 'SET_PRIVATE_DICTIONARIES';
export const SET_PUBLIC_DICTIONARIES = 'SET_PUBLIC_DICTIONARIES';
export const SET_RANGE = 'SET_RANGE';

export const LOADING_START = 'LOADING_START';
export const LOADING_FINISH = 'LOADING_FINISH';

export const SET_TASK_DICTIONARIES = 'SET_TASK_DICTIONARIES';