export const SET_RECEIVED_JSON = 'SET_RECEIVED_JSON';
export const SET_RECEIVED_TASK = 'SET_RECEIVED_TASK';
export const RM_TASK = 'RM_TASK';

export const SET_PRIVATE_DICTIONARIES = 'SET_PRIVATE_DICTIONARIES';
export const SET_PUBLIC_DICTIONARIES = 'SET_PUBLIC_DICTIONARIES';
export const SET_RANGE = 'SET_RANGE';
