export const SELECTED_FILE = 'SELECTED_FILE';
export const SET_REC_JSON = 'SET_REC_JSON';
export const CALL_BACKEND = 'CALL_BACKEND';
export const CALL_BACKEND_SUCCESS = 'CALL_BACKEND_SUCCESS';
export const CALL_BACKEND_FAILURE = 'CALL_BACKEND_FAILURE';

